### ISSUE TITLE
easier creation of ofxCvGrayscaleImage from raw depth pixels

### ISSUE THREAD

**Issue by robthepaper** [tyhenry/ofxRealSense#2]
Hi,
I've just installed the addon.
Was wondering if there are examples of a working project with ofxRealSense?
What should I include and how to init? is it the same methods as in mRSSDK addon?

thanks

**Comment by tyhenry** [comment]
Sorry for the lack of example - will try to add a simple one in next few days.
edit:  the interface is different than ofxRSSDK now

**Comment by tyhenry** [comment]
simple example showing color, depth, and mapped color<->depth images:

https://github.com/tyhenry/ofxRealSense/tree/master/example-simple

**Comment by robthepaper** [comment]
Thanks for the working example.
Do you have an example where I can work with pixels ? I would like to process the depth stream with ofxOpenCV functions.

**Comment by robthepaper** [comment]
For now I use getDepthRawPixelsRef().getColor(x,y) and copy to a image matrix (ofxCvGrayscaleImage). If there is a better way...

**Comment by tyhenry** [comment]
getDepthRawPixelsRef() is the right method to access accurate (raw) depth reading.

It returns a (grayscale) ofShortPixels reference - the brightness value of each pixel is the depth in centimeters.    The range is 16bit (unsigned short) so 0 - 65,535.

Good point, I should make it easier to send to ofxOpenCv.  Reopening this issue as a reminder.
I usually use [ofxCv](https://github.com/kylemcdonald/ofxCv) instead for OpenCV functions, as it's more flexible, and you can do something like:

EDIT - fixed:

    //const ofShortPixels& depthPix = realsense.getDepthRawPixelsRef();  // don't do this

    ofShortPixels depthPix = realsense.getDepthRawPixelsRef();  // *copy* the pixels
    Mat depthMat = toCv(depthPix); // native opencv image matrix

**Comment by robthepaper** [comment]
yep, got it for the 16 bits image.
Thanks for suggestion ofxCv, had no idea of its existence, gonna take a look at it!

**Comment by robthepaper** [comment]
hey, 
I tried to use ofxCv like you suggested but toCv() function doesn't take const ofShortPixels as argument.

For now I do this : 
```
const ofShortPixels& rawPixelsRef = realSense.getDepthRawPixelsRef();
ofShortPixels rawPixels = rawPixelsRef;
depthMat = toCv(rawPixels); // native opencv image matrix
```
Maybe I'm missing something?

Finallty did this :
```
ofShortPixels rawPixels = realSense.getDepthRawPixelsRef();
depthMat = toCv(rawPixels); // native opencv image matrix
```

**Comment by tyhenry** [comment]
Yep, sorry - my mistake in the code I posted above (fixed now).  You need to copy the pixels rather than use the reference (which shouldn't be altered directly, since those pixels belong to ofxRealSense, hence the const modifier)
